server:
  port: 8042
spring:
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        trace: false
        web-allow-others: true
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

contentmanagement:
  jwtCookieName: test
  jwtSecret: test123
  jwtExpirationMs: 300000